[package]
name = "GovFirst"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }

[addresses]
gov_first = "0xFFFF"
AptosFramework = "0x1"
